/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_davidawehr_cuda_example_JNINative */

#ifndef _Included_com_davidawehr_cuda_example_JNINative
#define _Included_com_davidawehr_cuda_example_JNINative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_davidawehr_cuda_example_JNINative
 * Method:    addArrays
 * Signature: ([F[F)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_davidawehr_cuda_1example_JNINative_addArrays
  (JNIEnv *, jclass, jfloatArray, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
